# network config
network:
  generator:
    data_dir: 'myeongdong_arr_4_rb_16'
    num_ue_range: [ 20, 40 ]
    num_rb: 4
    num_beam: 4
  environment:
    max_tx_power: 5
    num_tx_power_level: 17
    max_bs_power: 30
    noise_spectral_density: -174.0
    alpha: 0.0
    allow_reallocation: False
  graph:
    min_attn_db: -200
    max_attn_db: -50
    num_power_attn_level: 10
    prune_power_attn_thresh: -300

# model config
model:
  d_model: 512
  n_head: 16
  dim_feedforward: 512
  num_layers: 2
  dropout: 0.0
  activation: 'gelu'

# run config
run:
  num_episodes: 300
  num_simulations_per_episode: 32
  num_simulator: 16
  serve_num_replicas: 4
  serve_max_ongoing_requests: 35
  serve_max_batch_size: 32
  serve_batch_wait_timeout_s: 0.01
  num_training_workers: 4

# simulation config
simulation:
  gamma: 0.99  # for computing lambda returns
  lamb: 0.5  # for computing lambda returns (0: TD(1), 1: MC)
  max_num_steps: 500  # null if no limitation

# neural network train config
train:
  num_epochs_per_episode: 3
  batch_size: 64
  learning_rate: 0.0001
  act_prob_ratio_exponent_clip: 1.0
  ppo_clip: 0.1
  entropy_loss_weight: 0.05
  value_loss_weight: 1.0
  clip_max_norm: 1.0
